/**
 * # Header
 */

enum {
    DIALOG_ACCOUNT_LOGIN,
    DIALOG_ACCOUNT_REGISTRATION,
    DIALOG_CHARACTER_SELECTION,
    DIALOG_CHARACTER_ACTION,
    DIALOG_CHARACTER_CONFIRM_DELETE,
    DIALOG_CHARACTER_NAME_CREATION,
    DIALOG_CHARACTER_SEX_CREATION,
    DIALOG_CHARACTER_AGE_CREATION,
    DIALOG_CHARACTER_SKIN_CREATION
};